name: Run all tests inside repo/tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, linux, macOS, ARM64]

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cmake ../src
        make -j4
      working-directory: build
    - name: build_tests
      run: |
        cmake .
        make -j4
      working-directory: tests
    - name: run_tests
      run: |
        sudo ./run_all_tests
      working-directory: tests
