name: Run all tests inside repo/tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [Linux, macOS]
        arch: [ARM64]

    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cmake ../src
        make -j4
      working-directory: build
    - name: build_tests
      run: |
        cmake .
        make -j4
      working-directory: tests
    - name: run_tests
      run: |
        ./run_all_tests
      working-directory: tests
